parking copy/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'car_logs/home', to: 'car_logs#home'
  get 'car_logs/about', to: 'car_logs#about'
  resources :car_logs
  root to:'car_logs#home'
end

parking copy/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

parking copy/app/models/car_log.rb
class CarLog < ActiveRecord::Base
	validates :plate_number, presence: true, length: { maximum: 8 }
	self.table_name = "carlogs"
end

parking copy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

parking copy/app/controllers/car_logs_controller.rb
class CarLogsController < ApplicationController
	def home
		@carlogslast = CarLog.last
		if @carlogslast = nil
			flash[:notice] = "No existing car logs"
			redirect_to car_log_home_path
		else
			render 'new'
		end
	end
	def about
		@carlogslast = CarLog.last
		
	end
	def new
		@carlogs = CarLog.new
		@carlogslast = CarLog.last
	end
	def create
		@carlogs = CarLog.new(carlogs_params)
		if @carlogs.save
			flash[:notice] = "Created New Car Log"
			redirect_to car_log_path(@carlogs)
		else
			render 'new'
		end
	end
	def show
		@carlogs = CarLog.last
	end
	private
	def carlogs_params
		params.require(:car_log).permit(:plate_number, :time_in, :time_out, :color, :brand, :created_at, :updated_at)
	end
end

parking copy/app/helpers/application_helper.rb
module ApplicationHelper
end

parking copy/app/views/car_logs/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Parking Log: About</title>
	<style type="text/css">
		@font-face{
			font-family: "helpMeGod";
			src:url(/pls/pls.ttf);
		}
		@font-face{
			font-family: "iLoveJesus";
			src:url(/pls/omg.ttf);
		}
		h1,h2,p{
			color: white;
			font-family: "helpMeGod";
		}
		p{
			padding: 2em;
    		margin-bottom: 100px;
    		margin-right: 150px;
    		margin-left: 100px;
    		
		}
		h1{
			display: inline;
			letter-spacing: 10px;
		}
		h2{
			text-decoration: underline;
			letter-spacing: 3px;
		}
		nav{
			display: inline;
			float: right;
			position: relative;
			letter-spacing: 3px;
			padding-right: 100px;
		}
		.help{
			color: white;
			text-decoration: none;
			font-family: "iLoveJesus";
		}
	</style>
</head>
<body background = "/pls/hatdog.jpg">
	<h1>PARKING LOG</h1>
	<nav>
		<%= link_to "Home", car_logs_home_path, :class => "help"%>
		<%= link_to "About the Creator", car_logs_about_path, :class => "help"%>
		<%= link_to "Enter New Car", new_car_log_path, :class => "help"%>
		<%= link_to "Show Car", car_log_path(@carlogslast), :class => "help"%>
	</nav>
	<br>
	<img src = "/pls/meg.png" height = "500" width = "300" align="left" hspace="200" vspace="50">
	<h2> About the Creator</h2>
	<h2 style="text-decoration: none;">Meg Tuason</h2>
	<p>My nickname is Meg. I am a BS Management Information Systems student in Ateneo De Manila University. I like the sound of keyboards and the sound cats make when they want to play with something they can't reach. I like learning how to code and playing a guitar with new strings. I love rainy weather!!!!!! I don't really know anything about cars.</p>
</body>
</html>

parking copy/app/views/car_logs/home.html.erb
<!DOCTYPE html>
	<html>
	<head>
		<title>Parking Log</title>
		<style type="text/css">
			@font-face{
				font-family: "helpMeGod";
				src:url(/pls/pls.ttf);
			}
			h1{
				color: white;
				font-family: "helpMeGod";
				font-size: 50px;

			}
			.test{
				background-color: white;
    			width:200px;
    			font-size: 16px;
    			font-family: sans-serif;
			}
		</style>
	</head>
	<body background="/pls/hatdog.jpg">
		<img src = "/pls/car.png" height = "500" width = "650" align="left"hspace = "100"> 
		<br>
		<br>
		<br>
		<br>
		<br>
		<h1>PARKING LOG</h1>
		<%= button_to "Home", car_logs_home_path, :class => "test",:method=>:get%>
		<%= button_to "About Me", car_logs_about_path, :class => "test",:method=>:get%>
		<%= button_to "Enter New Car", new_car_log_path, :class => "test",:method=>:get%>
		<%= button_to "Show Car", car_log_path(@carlogslast), :class => "test",:method=>:get%>
		

	</body>
</html>

parking copy/app/views/car_logs/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Parking Log: New Car</title>
	<style type="text/css">
		@font-face{
			font-family: "helpMeGod";
			src:url(/pls/pls.ttf);
		}
		@font-face{
			font-family: "iLoveJesus";
			src:url(/pls/omg.ttf);
		}
		h1, h2, ul, p, h3{
			color: white;
			font-family: "helpMeGod";
		}
		nav{
			display: inline;
			float: right;
			position: relative;
			letter-spacing: 3px;
			padding-right: 100px;
			font-family: "iLoveJesus";
		}
		.help{
			color: white;
			text-decoration: none;
		}
		h1{
			display: inline;
			letter-spacing: 10px;
		}
	</style>
</head>
<body background = "/pls/hatdog.jpg">
	<h1>PARKING LOG</h1>
	<nav>
		<%= link_to "Home", car_logs_home_path, :class => "help"%>
		<%= link_to "About the Creator", car_logs_about_path, :class => "help"%>
		<%= link_to "Enter New Car", new_car_log_path, :class => "help"%>
		<%= link_to "Show Car", car_logs_path, :class => "help"%>
	</nav>
	<h2>Enter a New Car</h2>
	<% if @carlogs.errors.any? %>
	<h3> Errors: </h3>
		<ul>
			<% @carlogs.errors.full_messages.each do |msg| %>
			<%= msg %>
			<% end %>
		</ul>
	<% end %>
	<%= form_for @carlogs do |c| %>
	<p>
		<%= c.label :plate_number %>
		<%= c.text_field :plate_number %>
	</p>
	<p>
		<%= c.label :time_in %>
		<%= c.time_select :time_in %>
	</p>
	<p>
		<%= c.label :time_out %>
		<%= c.time_select :time_out %>
	</p>
	<p>
		<%= c.label :color %>
		<%= c.select :color, ['Black', 'White', 'Blue', 'Red', 'Silver', 'Yellow'] %>
	</p>
	<p>
		<%= c.label :brand %>
		<%= c.select :brand, ['Honda', 'Toyota', 'Ford', 'BMW', 'Mercedes', 'Ferrari', 'Hyundai', 'Porsche'] %>
	</p>
	<p>
		<%= c.label :created_at %>
		<%= c.date_select :created_at %>
	</p>
	<p>
		<%= c.label :updated_at %>
		<%= c.date_select :updated_at %>
	</p>
	<p>
		<%= c.submit %>
	</p>
	<% end %>
</body>
</html>

parking copy/app/views/car_logs/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Parking Log: Show Car</title>
	<style type="text/css">
		@font-face{
			font-family: "helpMeGod";
			src:url(/pls/pls.ttf);
		}
		@font-face{
			font-family: "iLoveJesus";
			src:url(/pls/omg.ttf);
		}
		h1{
			color: white;
			font-family: "helpMeGod";
			display: inline;
			letter-spacing: 10px;
		}
		nav{
			display: inline;
			float: right;
			position: relative;
			letter-spacing: 3px;
			padding-right: 100px;
			font-family: "iLoveJesus";
		}
		.help{
			color: white;
			text-decoration: none;
			font-family: "iLoveJesus";
		}
		h2{
			color: white;
			font-family: "helpMeGod"
			letter-spacing: 10px;
		}
		p{
			color: white;
			font-family: sans-serif;
		}
	</style>
</head>
<body background="/pls/hatdog.jpg">
	<h1>PARKING LOG</h1>
	<nav>
		<%= link_to "Home", car_logs_home_path, :class => "help"%>
		<%= link_to "About the Creator", car_logs_about_path, :class => "help"%>
		<%= link_to "Enter New Car", new_car_log_path, :class => "help"%>
		<%= link_to "Show Car", car_logs_path, :class => "help"%>
	</nav>
	<h2>Latest Car Log</h2>
	<p>
		PLATE NUMBER: <%= @carlogs.plate_number%>
	</p>
	<p>
		TIME IN: <%= @carlogs.time_in %>
	</p>
	<p>
		TIME OUT: <%= @carlogs.time_out %>
	</p>
	<p>
		COLOR: <%= @carlogs.color %>
	</p>
	<p>
		BRAND: <%= @carlogs.brand %>
	</p>
	<p>
		CREATED AT: <%= @carlogs.created_at %>
	</p>
	<p>
		UPDATED AT: <%= @carlogs.updated_at %>
	</p>

</body>
</html>

parking copy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>